### ISSUE TITLE
Support ansible loop:

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-policy#47]
I can't get it to handle this:

```
# Basic Lambda function deletion
- name: Delete Lambda functions HelloWorld and ByeBye
  lambda:
    name: '{{ item }}'
    state: absent
  loop:
    - HelloWorld
    - ByeBye
```

Here is my example policybook which I'm using against this:
```
### AWS lambda policy checks ###
---
- name: AWS Lambda based policy assurance checks
  hosts: localhost
  vars:
    essential_services:
    - "HelloWorld"
    - "AnotherOne"
  policies:
     - name: "Ensure we do not remove essential services"
       target: task
       condition:
         any:
         - input["amazon.aws.lambda"].name in essential_services and input["amazon.aws.lambda"].state == "absent" # if using FQCN
         - input["lambda"].name in essential_services and input["lambda"].state == "absent" # if not using FQCN
       actions:
         - deny:
             msg: Stopping the removal of essential Lambda services {{ essential_services }}
       tags:
         - compliance
```
